title: 我的博客
description: 简单可依赖的技术与随想
author: 宋雨竹
theme: jekyll-theme-primer   # GitHub Pages 自带，无需 remote_theme
url: "https://careyson.github.io"

# 先把分页关掉，等需要时再开
# paginate: 5
# paginate_path: "/page:num/"

plugins:
  - jekyll-feed              # 允许，Pages 自带
#  - jekyll-paginate         # 暂时注释
